In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
W_1=np.array([[2,-1,1,4],[-1,2,-3,1],[3,-2,-1,5]])
W_2=np.array([[3,1,-2,1],[-2,4,1,4],[-1,-3,2,-5],[3,1,1,1]])
W_3=np.array([[-1,3,-2],[1,-1,-3],[3,-2,2],[1,2,1]])
x_in=np.array([.5,.8,.2])
x_in


array([0.5, 0.8, 0.2])

In [3]:
x_mat_in = np.array([[.5,.8,.2],[.1,.9,.6],[.2,.2,.3],[.6,.1,.9],[.5,.5,.4],[.9,.1,.9],[.1,.8,.7]])
x_mat_in

array([[0.5, 0.8, 0.2],
       [0.1, 0.9, 0.6],
       [0.2, 0.2, 0.3],
       [0.6, 0.1, 0.9],
       [0.5, 0.5, 0.4],
       [0.9, 0.1, 0.9],
       [0.1, 0.8, 0.7]])

In [5]:
def soft_max_vec(vec):
    return np.exp(vec)/(np.sum(np.exp(vec)))

def soft_max_mat(mat):
    return np.exp(mat)/(np.sum(np.exp(mat),axis=1).reshape(-1,1))

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
#x_in single inputs
z1 = np.dot(x_in, W_1)
a1 = sigmoid(z1)

z2 = np.dot(a1, W_2)
a2 = sigmoid(z2)

z3 = np.dot(a2, W_3)
a3 = soft_max_vec(z3)

print("Layer 1 output:", a1)
print("Layer 2 output:", a2)
print("Final output (softmax):", a3)

Layer 1 output: [0.68997448 0.66818777 0.10909682 0.97811873]
Layer 2 output: [0.97231549 0.98225163 0.61882199 0.97801921]
Final output (softmax): [0.54648883 0.45132234 0.00218884]


In [9]:
def nn_single_input(x, W_1, W_2, W_3):
    z1 = np.dot(x, W_1)
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W_2)
    a2 = sigmoid(z2)

    z3 = np.dot(a2, W_3)
    a3 = soft_max_vec(z3)

    return a3

#matrix input func
def nn_matrix_input(X, W_1, W_2, W_3):
    Z1 = np.dot(X, W_1)
    A1 = sigmoid(Z1)

    Z2 = np.dot(A1, W_2)
    A2 = sigmoid(Z2)

    Z3 = np.dot(A2, W_3)
    A3 = soft_max_mat(Z3)

    return A3

# For single input
output_single = nn_single_input(x_in, W_1, W_2, W_3)
print("Output for single input:", output_single)

# For matrix input
output_matrix = nn_matrix_input(x_mat_in, W_1, W_2, W_3)
print("Output for matrix input:\n", output_matrix)

Output for single input: [0.54648883 0.45132234 0.00218884]
Output for matrix input:
 [[0.54648883 0.45132234 0.00218884]
 [0.44817105 0.54992765 0.00190131]
 [0.53819061 0.45892803 0.00288136]
 [0.32245805 0.67433443 0.00320753]
 [0.41670093 0.58125627 0.0020428 ]
 [0.3492107  0.64658121 0.00420809]
 [0.37718187 0.62109819 0.00171995]]
